# Generated by Django 3.1.2 on 2020-11-20 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewCases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500, null=True)),
                ('xcoord', models.FloatField()),
                ('ycoord', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitedLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFrom', models.DateField()),
                ('dateTo', models.DateField()),
                ('category', models.CharField(max_length=20)),
                ('caseRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewCases.caserecord')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addLocation.location')),
            ],
        ),
    ]
